/**
 * The spellbook — every incantation the castle will ask you for.
 *
 * `tier` is how hard the word is to say, not how strong the spell is — 1 is a
 * word you can bark, 3 is a mouthful you will fumble the first three times.
 * The game ramps tiers with the floor, so the difficulty curve is your tongue.
 *
 * `effect` is the funny one. A spell that only subtracts a number is a number;
 * these do something visible and stupid to the thing in front of you, and
 * `reaction` is the line that flashes when it lands.
 *
 * `spoken` is the load-bearing field. Browser speech recognition handed an
 * invented Latin word does not return a near-miss of it — it returns the
 * nearest English it can assemble. Every entry here is a real thing a
 * recogniser comes back with, and the scorer treats them as correct.
 *
 * ── Two rules for adding words, both learned the hard way ──
 *
 * 1. SEVEN CHARACTERS MINIMUM, spaces not counted. The match threshold allows
 *    three characters of slop in absolute terms (`thresholdFor` in voice.js),
 *    which on a five-letter word is most of the word — anything that short
 *    fires on ordinary conversation. There is no short spell here that is worth
 *    that; where canon has one, the two-word form is used (LUMOS → LUMOS
 *    MAXIMA).
 *
 * 2. RUN `node tools/word-audit.mjs` BEFORE AND AFTER. With one word on screen
 *    at a time, two spells that sound alike used to cost nothing, and the
 *    matcher was widened on exactly that argument. It stops being free at this
 *    size: a bank this large has to reach past invented Latin into words that
 *    sound like English, and every one of those is a chance for the game to
 *    fire while the player is talking to someone else in the room. The audit is
 *    the check that the bank is still made of distinctive sounds.
 *
 * Not all of it is Harry Potter, on purpose — stage magic, alchemy, and a
 * couple of things borrowed from elsewhere entirely. A hundred words of one
 * flavour is a list; a hundred words of five flavours is a spellbook.
 */

export const SPELLS = [
  /* ── tier 1: short, barkable ─────────────────────────────────────── */
  {
    word: 'STUPEFY',
    tier: 1,
    spoken: ['stupefy', 'stupify', 'stupefied', 'stupa fy', 'stew pify', 'to pacify'],
    color: 0xff3b30,
    glow: 0xff8a6a,
    damage: 34,
    speed: 46,
    radius: 0,
    note: 'a red bolt, straight to the chest',
    reaction: 'It drops like a sack of bricks.',
  },
  {
    word: 'INCENDIO',
    tier: 1,
    spoken: ['incendio', 'in cendio', 'insendio', 'in send io', 'incendia', 'in san diego'],
    color: 0xff6a1a,
    glow: 0xffb066,
    damage: 22,
    speed: 34,
    radius: 3.4,
    burn: true,
    note: 'a gout of flame that keeps burning',
    reaction: 'Something back there is on fire now.',
  },
  {
    word: 'BOMBARDA',
    tier: 1,
    spoken: ['bombarda', 'bombardo', 'bomb arda', 'bombarder', 'bum barda', 'bomb barda'],
    color: 0xbfe8ff,
    glow: 0xffffff,
    damage: 48,
    speed: 30,
    radius: 4.6,
    note: 'blast radius, so aim into the crowd',
    reaction: 'The corridor rearranges itself.',
  },
  {
    word: 'REDUCTO',
    tier: 1,
    spoken: ['reducto', 'reductor', 'reduce toe', 'reduct o', 'ridotto', 'red duct o'],
    color: 0xc07bff,
    glow: 0xe4c4ff,
    damage: 40,
    speed: 62,
    radius: 0,
    pierce: true,
    note: 'punches through everything in the lane',
    reaction: 'Straight through. And through the next one.',
  },
  {
    word: 'DIFFINDO',
    tier: 1,
    spoken: ['diffindo', 'difindo', 'diff indo', 'defiendo', 'the fiendo'],
    color: 0x9ef0d0,
    glow: 0xdffff2,
    damage: 30,
    speed: 58,
    radius: 0,
    note: 'a clean severing charm',
    reaction: 'Cut neatly in half. Both halves look annoyed.',
  },
  {
    word: 'CONFRINGO',
    tier: 1,
    spoken: ['confringo', 'con fringo', 'confringe o', 'kon fringo', 'con flamingo'],
    color: 0xffa23d,
    glow: 0xffe0b0,
    damage: 38,
    speed: 40,
    radius: 3.8,
    note: 'the blasting curse',
    reaction: 'Everything nearby is briefly airborne.',
  },
  {
    // Not REDUCIO, which is the canon shrinking charm — one letter from
    // REDUCTO, already in this list. Two words that differ by a letter are a
    // scoring coin-flip, and losing a coin-flip reads as a broken engine.
    word: 'DIMINUENDO',
    tier: 1,
    spoken: ['diminuendo', 'diminuento', 'dimin uendo', 'the minuendo'],
    color: 0x7fd8ff,
    glow: 0xd9f4ff,
    damage: 10,
    speed: 52,
    radius: 0,
    effect: 'shrink',
    note: 'shrinks it to something you can step on',
    reaction: 'It is now the size of a teapot and furious about it.',
  },
  {
    word: 'ALOHOMORA',
    tier: 1,
    spoken: ['alohomora', 'aloha mora', 'a loh a mora', 'alo homora', 'aloe ha mora'],
    color: 0xffd98a,
    glow: 0xfff0cc,
    damage: 26,
    speed: 54,
    radius: 0,
    note: 'the unlocking charm, used rudely',
    reaction: 'Something inside it just came unlatched.',
  },
  {
    word: 'CONFUNDO',
    tier: 1,
    spoken: ['confundo', 'con fundo', 'confound o', 'confundle', 'con fun though'],
    color: 0xb9a0ff,
    glow: 0xe4d8ff,
    damage: 16,
    speed: 50,
    radius: 2.6,
    effect: 'dance',
    note: 'it forgets which way it was going',
    reaction: 'It has completely lost the thread.',
  },
  {
    word: 'DEPULSO',
    tier: 1,
    spoken: ['depulso', 'de pulso', 'the pulso', 'dee pulse o', 'depulse'],
    color: 0x8fd0ff,
    glow: 0xdcf0ff,
    damage: 20,
    speed: 56,
    radius: 2.2,
    knockback: 8,
    note: 'the banishing charm — shoves it back',
    reaction: 'Sent back the way it came, at speed.',
  },
  {
    word: 'EVANESCO',
    tier: 1,
    spoken: ['evanesco', 'evan esco', 'ever nesco', 'even esco', 'evanescent'],
    color: 0xd0d0e8,
    glow: 0xf4f4ff,
    damage: 36,
    speed: 60,
    radius: 0,
    note: 'the vanishing spell',
    reaction: 'Gone. No fuss, no remains.',
  },
  {
    word: 'FLIPENDO',
    tier: 1,
    spoken: ['flipendo', 'flip endo', 'flippin do', 'flee pendo', 'flip window'],
    color: 0x7ae0ff,
    glow: 0xd4f6ff,
    damage: 24,
    speed: 58,
    radius: 0,
    effect: 'trip',
    note: 'the knockback jinx',
    reaction: 'Flipped clean over onto its back.',
  },
  {
    word: 'GLACIUS',
    tier: 1,
    spoken: ['glacius', 'glay shus', 'glacier us', 'gla see us', 'glacius'],
    color: 0xa8e8ff,
    glow: 0xe8faff,
    damage: 18,
    speed: 52,
    radius: 3.0,
    effect: 'freeze',
    note: 'freezes the air around it solid',
    reaction: 'Frozen stiff, with a look of complaint.',
  },
  {
    word: 'SILENCIO',
    tier: 1,
    spoken: ['silencio', 'silence io', 'si lencio', 'silencia', 'san lencio'],
    color: 0x9aa8c8,
    glow: 0xdde4f4,
    damage: 28,
    speed: 54,
    radius: 0,
    note: 'the silencing charm',
    reaction: 'It is still shouting. Nothing is coming out.',
  },
  {
    word: 'LANGLOCK',
    tier: 1,
    spoken: ['langlock', 'lang lock', 'lane lock', 'long lock', 'lang loch'],
    color: 0xffb0d8,
    glow: 0xffe0f0,
    damage: 22,
    speed: 56,
    radius: 0,
    effect: 'laugh',
    note: 'glues its tongue to the roof of its mouth',
    reaction: 'Tongue stuck fast. It has given up on threats.',
  },
  {
    word: 'DESCENDO',
    tier: 1,
    spoken: ['descendo', 'de scendo', 'descend o', 'the scendo', 'dissenting'],
    color: 0xc8b0ff,
    glow: 0xeee4ff,
    damage: 32,
    speed: 44,
    radius: 2.4,
    note: 'brings the ceiling down on it',
    reaction: 'Whatever was above it is on it now.',
  },
  {
    word: 'ASCENDIO',
    tier: 1,
    spoken: ['ascendio', 'a scendio', 'ascend io', 'as send io', 'ascending'],
    color: 0xd8f0ff,
    glow: 0xffffff,
    damage: 12,
    speed: 50,
    radius: 0,
    effect: 'levitate',
    note: 'launches it straight up',
    reaction: 'Straight up into the vaulting. It will be a moment.',
  },
  {
    word: 'IMPERIO',
    tier: 1,
    spoken: ['imperio', 'im perio', 'imperial', 'in perio', 'em perio'],
    color: 0x9fe0b0,
    glow: 0xdcf8e4,
    damage: 14,
    speed: 58,
    radius: 0,
    effect: 'dance',
    note: 'it takes orders from you now',
    reaction: 'It is dancing. It was not asked to, and yet.',
  },
  {
    word: 'RELASHIO',
    tier: 1,
    spoken: ['relashio', 're lashio', 'relation', 'rela shio', 'ray lashio'],
    color: 0xff8a4a,
    glow: 0xffd4b0,
    damage: 30,
    speed: 48,
    radius: 2.0,
    burn: true,
    note: 'a lash of sparks that keeps biting',
    reaction: 'Sparks all over it, and they are not going out.',
  },
  {
    word: 'FLAGRATE',
    tier: 1,
    spoken: ['flagrate', 'fla grate', 'flagrant', 'flag rate', 'flay grate'],
    color: 0xff9a2a,
    glow: 0xffdc9a,
    damage: 26,
    speed: 50,
    radius: 0,
    burn: true,
    note: 'draws a burning line through it',
    reaction: 'A line of fire, drawn straight through the middle.',
  },
  {
    word: 'MELOFORS',
    tier: 1,
    spoken: ['melofors', 'melo fors', 'mellow fors', 'melafors', 'mellow force'],
    color: 0xffc84a,
    glow: 0xffeeb8,
    damage: 20,
    speed: 46,
    radius: 0,
    effect: 'grow',
    note: 'encases its head in a pumpkin',
    reaction: 'Its head is a pumpkin. It cannot see a thing.',
  },
  {
    word: 'GEMINIO',
    tier: 1,
    spoken: ['geminio', 'gemin io', 'gemini o', 'jem in io', 'gemini'],
    color: 0xc0e8ff,
    glow: 0xeafaff,
    damage: 38,
    speed: 60,
    radius: 0,
    pierce: true,
    note: 'the bolt copies itself as it goes',
    reaction: 'One went in. Several came out the far side.',
  },
  {
    word: 'DEPRIMO',
    tier: 1,
    spoken: ['deprimo', 'de primo', 'depri mo', 'the primo', 'deep reemo'],
    color: 0x8f9ac0,
    glow: 0xd8e0f4,
    damage: 42,
    speed: 38,
    radius: 3.2,
    note: 'blows the floor out from under it',
    reaction: 'The flagstones under it are no longer there.',
  },
  {
    word: 'EBUBLIO',
    tier: 1,
    spoken: ['ebublio', 'e bublio', 'ebubblio', 'a bubblio', 'ee bublio'],
    color: 0x7fe8e0,
    glow: 0xd8fffb,
    damage: 16,
    speed: 44,
    radius: 2.8,
    effect: 'levitate',
    note: 'seals it inside a bubble',
    reaction: 'Sealed in a bubble, bobbing gently, incandescent.',
  },
  {
    word: 'EPISKEY',
    tier: 1,
    spoken: ['episkey', 'epi skey', 'a piskey', 'epis key', 'epic key'],
    color: 0xa8ffc0,
    glow: 0xe4fff0,
    damage: 24,
    speed: 62,
    radius: 0,
    note: 'a healing charm, cast with hostile intent',
    reaction: 'Healed. Violently. It did not enjoy it.',
  },
  {
    word: 'ABRAXAS',
    tier: 1,
    spoken: ['abraxas', 'abra xas', 'a braxas', 'abraxis', 'a bracket us'],
    color: 0xff7ac0,
    glow: 0xffd8ee,
    damage: 34,
    speed: 48,
    radius: 2.0,
    note: 'a name older than the castle',
    reaction: 'Something very old just took an interest.',
  },
  {
    word: 'ATHANOR',
    tier: 1,
    spoken: ['athanor', 'atha nor', 'a thanor', 'athenor', 'a than or'],
    color: 0xff8c30,
    glow: 0xffd0a0,
    damage: 28,
    speed: 42,
    radius: 3.0,
    burn: true,
    note: "the alchemist's furnace, opened at it",
    reaction: 'The air in front of it turns into a furnace.',
  },
  {
    word: 'VITRIOL',
    tier: 1,
    spoken: ['vitriol', 'vit riol', 'vitriolic', 'victriol', 'vitri ol'],
    color: 0x9fe04a,
    glow: 0xdcf8b0,
    damage: 32,
    speed: 46,
    radius: 0,
    burn: true,
    note: 'oil of vitriol, thrown',
    reaction: 'It is dissolving, and it has noticed.',
  },
  {
    word: 'ALKAHEST',
    tier: 1,
    spoken: ['alkahest', 'alka hest', 'al kahest', 'alkahaste', 'alka heist'],
    color: 0xb8ff8a,
    glow: 0xe8ffd0,
    damage: 44,
    speed: 40,
    radius: 0,
    pierce: true,
    note: 'the universal solvent — dissolves anything',
    reaction: 'It went through that one and kept dissolving.',
  },
  {
    word: 'NIGREDO',
    tier: 1,
    spoken: ['nigredo', 'ni gredo', 'negredo', 'nig redo', 'knee gredo'],
    color: 0x6a5a8a,
    glow: 0xc0b0dc,
    damage: 30,
    speed: 50,
    radius: 0,
    effect: 'freeze',
    note: 'the blackening — the first stage of the work',
    reaction: 'It has gone black and completely still.',
  },
  {
    word: 'HEY PRESTO',
    tier: 1,
    spoken: ['hey presto', 'hay presto', 'hey pesto', 'a presto', 'hey press toe'],
    color: 0xff9ae8,
    glow: 0xffdcf6,
    damage: 30,
    speed: 56,
    radius: 2.2,
    note: 'stage magic, delivered with contempt',
    reaction: 'Ta-da. It is not applauding.',
  },

  /* ── tier 2: the ones you have to slow down for ──────────────────── */
  {
    word: 'EXPELLIARMUS',
    tier: 2,
    spoken: [
      'expelliarmus', 'expeliarmus', 'expelly armus', 'expel he armus',
      'a spell he armas', 'expel yarmouth', 'expel the armors',
    ],
    color: 0xffc23d,
    glow: 0xffe6a0,
    damage: 26,
    speed: 54,
    radius: 2.4,
    knockback: 7,
    note: 'disarms, and throws them back',
    reaction: 'Disarmed, and sent back down the corridor.',
  },
  {
    word: 'IMPEDIMENTA',
    tier: 2,
    spoken: ['impedimenta', 'impediment a', 'impediment', 'impede a menta', 'in pedimenta'],
    color: 0x8fd0ff,
    glow: 0xdbefff,
    damage: 16,
    speed: 50,
    radius: 3.0,
    effect: 'freeze',
    note: 'stops it dead where it stands',
    reaction: 'Frozen mid-stride, one foot still up.',
  },
  {
    word: 'LEVICORPUS',
    tier: 2,
    spoken: ['levicorpus', 'levi corpus', 'levy corpus', 'levi corpse', 'heavy corpus'],
    color: 0xc9f0ff,
    glow: 0xffffff,
    damage: 14,
    speed: 48,
    radius: 0,
    effect: 'levitate',
    note: 'hoists it into the air by the ankle',
    reaction: 'Hanging upside down by one ankle, flailing.',
  },
  {
    word: 'RICTUSEMPRA',
    tier: 2,
    spoken: ['rictusempra', 'rictus empra', 'rictus sempra', 'rick to sempra', 'ricky sempra'],
    color: 0xffe27a,
    glow: 0xfff6d0,
    damage: 12,
    speed: 56,
    radius: 0,
    effect: 'laugh',
    note: 'the tickling charm',
    reaction: 'It doubles over laughing. It cannot advance while laughing.',
  },
  {
    word: 'ENGORGIO',
    tier: 2,
    spoken: ['engorgio', 'en gorgio', 'in gorgio', 'and gorgio', 'in georgia'],
    color: 0xff8fd0,
    glow: 0xffd6ee,
    damage: 18,
    speed: 44,
    radius: 0,
    effect: 'grow',
    note: 'inflates it until it is a liability',
    reaction: 'Now enormous, slow, and extremely easy to hit.',
  },
  {
    word: 'FURNUNCULUS',
    tier: 2,
    spoken: ['furnunculus', 'fur nunculus', 'furuncle us', 'fernunculus', 'for uncle us'],
    color: 0x9fe07a,
    glow: 0xdcf7c4,
    damage: 28,
    speed: 46,
    radius: 2.2,
    note: 'covers it in boils',
    reaction: 'Boils. Everywhere. It has stopped caring about you.',
  },
  {
    word: 'EXPECTO PATRONUM',
    tier: 2,
    spoken: [
      'expecto patronum', 'expecto patronium', 'expect o patronum',
      'expecto patron', 'expect a patronum', 'espresso patronum',
    ],
    color: 0xdff4ff,
    glow: 0xffffff,
    damage: 30,
    speed: 26,
    radius: 7.5,
    note: 'a stag of light — clears the corridor',
    reaction: 'A stag of light goes through the lot of them.',
  },
  {
    word: 'LUMOS MAXIMA',
    tier: 2,
    spoken: ['lumos maxima', 'lumos maximus', 'loomos maxima', 'lu mos maxima', 'lumen maxima'],
    color: 0xfff4d0,
    glow: 0xffffff,
    damage: 34,
    speed: 58,
    radius: 3.4,
    note: 'a sun, briefly, at arm’s length',
    reaction: 'For half a second the corridor has a sun in it.',
  },
  {
    word: 'AGUAMENTI',
    tier: 2,
    spoken: ['aguamenti', 'agua menti', 'aqua menti', 'agua mente', 'a gwar menti'],
    color: 0x5ac8ff,
    glow: 0xc8ecff,
    damage: 24,
    speed: 48,
    radius: 3.2,
    knockback: 5,
    note: 'a jet of water, hard enough to hurt',
    reaction: 'Blasted off its feet and thoroughly soaked.',
  },
  {
    word: 'COLLOPORTUS',
    tier: 2,
    spoken: ['colloportus', 'collo portus', 'colo portus', 'call a portus', 'colloportis'],
    color: 0xb08aff,
    glow: 0xe0d0ff,
    damage: 20,
    speed: 46,
    radius: 0,
    effect: 'freeze',
    note: 'seals it shut where it stands',
    reaction: 'Sealed shut. All of it. Including the legs.',
  },
  {
    word: 'IMMOBULUS',
    tier: 2,
    spoken: ['immobulus', 'immo bulus', 'im mobulus', 'a mobulus', 'immobile us'],
    color: 0xbfe0ff,
    glow: 0xeaf6ff,
    damage: 18,
    speed: 52,
    radius: 3.6,
    effect: 'freeze',
    note: 'stops everything in the blast',
    reaction: 'The whole group stops, mid-step, like a photograph.',
  },
  {
    word: 'INCARCEROUS',
    tier: 2,
    spoken: ['incarcerous', 'in carcerous', 'incarcerus', 'in cars are us', 'incarcerate us'],
    color: 0xc8a878,
    glow: 0xf0e0c8,
    damage: 22,
    speed: 50,
    radius: 0,
    effect: 'freeze',
    note: 'ropes, from nowhere, a lot of them',
    reaction: 'Wrapped in rope from the shoulders down.',
  },
  {
    word: 'MOBILICORPUS',
    tier: 2,
    spoken: ['mobilicorpus', 'mobili corpus', 'mobile corpus', 'mobilee corpus', 'mobility corpus'],
    color: 0xd8c8ff,
    glow: 0xf0eaff,
    damage: 16,
    speed: 48,
    radius: 0,
    effect: 'dance',
    note: 'walks it around like a puppet',
    reaction: 'Marched about on strings it cannot see.',
  },
  {
    word: 'MUFFLIATO',
    tier: 2,
    spoken: ['muffliato', 'muffle ato', 'muffli ato', 'muff liato', 'muffle otto'],
    color: 0xa8b0c8,
    glow: 0xdee4f0,
    damage: 26,
    speed: 54,
    radius: 2.8,
    note: 'fills its head with buzzing',
    reaction: 'It can hear nothing but bees now.',
  },
  {
    word: 'REPARIFORS',
    tier: 2,
    spoken: ['reparifors', 'repari fors', 'repair a force', 'reparifours', 'repartee force'],
    color: 0x8affc8,
    glow: 0xd8ffe8,
    damage: 28,
    speed: 56,
    radius: 0,
    note: 'undoes it, in the unhelpful sense',
    reaction: 'Repaired into a shape that does not work.',
  },
  {
    word: 'WADDIWASI',
    tier: 2,
    spoken: ['waddiwasi', 'waddi wasi', 'wadi wasi', 'waddy wassy', 'what he was he'],
    color: 0xffb060,
    glow: 0xffe0c0,
    damage: 32,
    speed: 60,
    radius: 0,
    note: 'fires whatever is loose, hard',
    reaction: 'Hit by something that used to be part of the wall.',
  },
  {
    word: 'MORSMORDRE',
    tier: 2,
    spoken: ['morsmordre', 'mors mordre', 'morse mordre', 'mors morder', 'moss murder'],
    color: 0x8ade8a,
    glow: 0xd0f4d0,
    damage: 40,
    speed: 40,
    radius: 4.2,
    note: 'a very rude thing to put in the sky',
    reaction: 'Something enormous and green unfolds overhead.',
  },
  {
    word: 'DENSAUGEO',
    tier: 2,
    spoken: ['densaugeo', 'densau geo', 'den saugeo', 'dense augeo', 'densaugio'],
    color: 0xfff0f0,
    glow: 0xffffff,
    damage: 22,
    speed: 52,
    radius: 0,
    effect: 'grow',
    note: 'its teeth keep going',
    reaction: 'The teeth have reached the floor and are still going.',
  },
  {
    word: 'DUCKLIFORS',
    tier: 2,
    spoken: ['ducklifors', 'duckli fors', 'duck liffors', 'ducky force', 'duckli force'],
    color: 0xffd84a,
    glow: 0xfff2b8,
    damage: 12,
    speed: 54,
    radius: 0,
    effect: 'shrink',
    note: 'turns it into a duck',
    reaction: 'It is a duck. It is furious about being a duck.',
  },
  {
    word: 'HERBIVICUS',
    tier: 2,
    spoken: ['herbivicus', 'herbi vicus', 'herb ivicus', 'herbivorous', 'herbie vicus'],
    color: 0x7ade5a,
    glow: 0xd4f8c0,
    damage: 26,
    speed: 44,
    radius: 3.0,
    effect: 'freeze',
    note: 'the corridor grows through it',
    reaction: 'Roots have come through the flagstones and taken it.',
  },
  {
    word: 'PERICULUM',
    tier: 2,
    spoken: ['periculum', 'peri culum', 'pericolum', 'perry culum', 'particular'],
    color: 0xff5a3a,
    glow: 0xffc0b0,
    damage: 34,
    speed: 62,
    radius: 0,
    note: 'a distress flare, fired point-blank',
    reaction: 'A red flare, straight through the middle of it.',
  },
  {
    word: 'SALVIO HEXIA',
    tier: 2,
    spoken: ['salvio hexia', 'salvio hexi a', 'salvia hexia', 'salvio hex', 'save you hexia'],
    color: 0xa0f0d8,
    glow: 0xdcfff4,
    damage: 24,
    speed: 50,
    radius: 3.4,
    knockback: 6,
    note: 'a ward, slammed outward',
    reaction: 'The air itself shoves them back down the corridor.',
  },
  {
    word: 'ABRACADABRA',
    tier: 2,
    spoken: ['abracadabra', 'abra cadabra', 'abraca dabra', 'abrakadabra', 'a brack a dabra'],
    color: 0xff8a3d,
    glow: 0xffd8a8,
    damage: 40,
    speed: 46,
    radius: 3.0,
    note: 'the original, from long before the castle',
    reaction: 'The oldest word in the book still works.',
  },
  {
    word: 'HOCUS POCUS',
    tier: 2,
    spoken: ['hocus pocus', 'hocus focus', 'hoke us pokus', 'hocus poke us', 'okus pokus'],
    color: 0xc86aff,
    glow: 0xe8c8ff,
    damage: 28,
    speed: 52,
    radius: 2.6,
    effect: 'shrink',
    note: 'stage patter with real consequences',
    reaction: 'Pocket-sized, and deeply offended.',
  },
  {
    word: 'OPEN SESAME',
    tier: 2,
    spoken: ['open sesame', 'open sesamee', 'opens a me', 'open sesamy', 'open says a me'],
    color: 0xffcf6a,
    glow: 0xffedc4,
    damage: 32,
    speed: 48,
    radius: 3.2,
    note: 'it opens things that were shut',
    reaction: 'It came open. All of it. At once.',
  },
  {
    word: 'MUMBO JUMBO',
    tier: 2,
    spoken: ['mumbo jumbo', 'mumbo dumbo', 'mum bo jumbo', 'mumba jumba', 'number jumbo'],
    color: 0x8affd0,
    glow: 0xd8fff0,
    damage: 18,
    speed: 50,
    radius: 2.8,
    effect: 'dance',
    note: 'nonsense, but load-bearing nonsense',
    reaction: 'Whatever that was, it worked, and nobody knows why.',
  },
  {
    word: 'SIM SALA BIM',
    tier: 2,
    spoken: ['sim sala bim', 'simsala bim', 'sim salabim', 'sim sarah bim', 'seem sala bim'],
    color: 0xffa8f0,
    glow: 0xffe0fa,
    damage: 30,
    speed: 54,
    radius: 0,
    effect: 'trip',
    note: 'a conjurer’s word, borrowed without asking',
    reaction: 'Its legs stopped believing in it.',
  },
  {
    word: 'PRESTO CHANGO',
    tier: 2,
    spoken: ['presto chango', 'presto change o', 'press toe chango', 'presto chango', 'pesto chango'],
    color: 0xff70a8,
    glow: 0xffd0e4,
    damage: 20,
    speed: 56,
    radius: 0,
    effect: 'grow',
    note: 'changes it into something worse at walking',
    reaction: 'Changed into something enormous and badly balanced.',
  },
  {
    word: 'OUROBOROS',
    tier: 2,
    spoken: ['ouroboros', 'ouro boros', 'oro boros', 'aurora boros', 'euro boros'],
    color: 0x6ad8b0,
    glow: 0xc8f4e4,
    damage: 26,
    speed: 44,
    radius: 0,
    effect: 'trip',
    note: 'the serpent that eats its own tail',
    reaction: 'It is chasing its own tail and cannot stop.',
  },
  {
    word: 'QUINTESSENCE',
    tier: 2,
    spoken: ['quintessence', 'quint essence', 'quintessential', 'kwint essence', 'quinte sense'],
    color: 0xe0d0ff,
    glow: 0xf6f0ff,
    damage: 36,
    speed: 42,
    radius: 4.0,
    note: 'the fifth element, applied bluntly',
    reaction: 'Reduced to its constituent parts, quite tidily.',
  },
  {
    word: 'PRIMA MATERIA',
    tier: 2,
    spoken: ['prima materia', 'prima material', 'primer materia', 'prima mater ia', 'prime a materia'],
    color: 0xb0a0d0,
    glow: 0xe4dcf4,
    damage: 22,
    speed: 40,
    radius: 3.6,
    effect: 'shrink',
    note: 'back to the raw stuff it was made from',
    reaction: 'Unmade back into the stuff it started as.',
  },
  {
    word: 'FULMINARE',
    tier: 2,
    spoken: ['fulminare', 'fulmin are', 'ful minare', 'fulminate', 'full minari'],
    color: 0xd8f0ff,
    glow: 0xffffff,
    damage: 42,
    speed: 64,
    radius: 0,
    pierce: true,
    note: 'a lightning bolt, in the literal sense',
    reaction: 'The whole corridor lit white for an instant.',
  },
  {
    word: 'CATACLYSMUS',
    tier: 2,
    spoken: ['cataclysmus', 'cata clysmus', 'cataclysm us', 'kata clysmus', 'cataclysmic'],
    color: 0xff6a4a,
    glow: 0xffc8b0,
    damage: 44,
    speed: 34,
    radius: 5.0,
    knockback: 4,
    note: 'more than the situation requires',
    reaction: 'That was far more than the situation required.',
  },
  {
    word: 'PYROCLASMA',
    tier: 2,
    spoken: ['pyroclasma', 'pyro clasma', 'pyroclastic', 'pyro plasma', 'pie ro clasma'],
    color: 0xff5a20,
    glow: 0xffc090,
    damage: 30,
    speed: 36,
    radius: 4.4,
    burn: true,
    note: 'a wave of burning ash',
    reaction: 'A wave of ash goes down the corridor, still burning.',
  },
  {
    word: 'TEMPESTAS',
    tier: 2,
    spoken: ['tempestas', 'tempes tas', 'tempest as', 'tempestus', 'tempest ass'],
    color: 0x7ab8ff,
    glow: 0xd0e8ff,
    damage: 26,
    speed: 46,
    radius: 4.8,
    knockback: 6,
    note: 'weather, indoors',
    reaction: 'There is weather in the corridor now, and it is bad.',
  },
  {
    word: 'SOMNIFERUM',
    tier: 2,
    spoken: ['somniferum', 'somni ferum', 'som niferum', 'somniferous', 'somni forum'],
    color: 0xb0a0e8,
    glow: 0xe4dcfa,
    damage: 16,
    speed: 44,
    radius: 3.0,
    effect: 'freeze',
    note: 'it goes to sleep on its feet',
    reaction: 'Fast asleep, standing up, still facing you.',
  },
  {
    word: 'MITHRANDIR',
    tier: 2,
    spoken: ['mithrandir', 'mith randir', 'mithra ndir', 'mithrander', 'with random dear'],
    color: 0xdce8ff,
    glow: 0xffffff,
    damage: 40,
    speed: 44,
    radius: 3.2,
    knockback: 5,
    note: 'borrowed from a different set of books entirely',
    reaction: 'It shall not pass. It is not passing.',
  },
  {
    word: 'IGNIS FATUUS',
    tier: 2,
    spoken: ['ignis fatuus', 'ignis fatuous', 'igniss fatuus', 'ignis fat you us', 'ignus fatuus'],
    color: 0x8affaa,
    glow: 0xd8ffe0,
    damage: 20,
    speed: 38,
    radius: 2.6,
    burn: true,
    effect: 'dance',
    note: 'a will-o-the-wisp, leading it nowhere',
    reaction: 'Chasing a light that is not there and never was.',
  },
  {
    word: 'DISINTEGRO',
    tier: 2,
    spoken: ['disintegro', 'disinte gro', 'disintegrate o', 'dis integro', 'disin tegro'],
    color: 0xff7a9a,
    glow: 0xffd0dc,
    damage: 46,
    speed: 50,
    radius: 0,
    pierce: true,
    note: 'takes it apart at the seams',
    reaction: 'Came apart in the order it was assembled.',
  },

  /* ── tier 3: tongue-twisters ─────────────────────────────────────── */
  {
    word: 'TARANTALLEGRA',
    tier: 3,
    spoken: [
      'tarantallegra', 'tarantella gra', 'tarantula legra', 'tarantallegro',
      'tarantella allegra', 'tarantula allegra',
    ],
    color: 0xff6ad5,
    glow: 0xffd4f2,
    damage: 14,
    speed: 50,
    radius: 2.6,
    effect: 'dance',
    note: 'makes its legs dance without permission',
    reaction: 'Its legs have started dancing. The rest of it disapproves.',
  },
  {
    word: 'PETRIFICUS TOTALUS',
    tier: 3,
    spoken: [
      'petrificus totalus', 'petrificus totalis', 'petrify us totalus',
      'pacificus totalus', 'petrificus total us', 'terrific is totalus',
    ],
    color: 0xa8b8d8,
    glow: 0xe6eeff,
    damage: 26,
    speed: 44,
    radius: 0,
    effect: 'freeze',
    note: 'full body-bind',
    reaction: 'Rigid as a plank. Falls over like one too.',
  },
  {
    word: 'LOCOMOTOR MORTIS',
    tier: 3,
    spoken: [
      'locomotor mortis', 'loco motor mortis', 'locomotive mortis',
      'locomotor morris', 'loco motor mortise',
    ],
    color: 0x7ad4ff,
    glow: 0xd6f2ff,
    damage: 20,
    speed: 52,
    radius: 0,
    effect: 'trip',
    note: 'locks the legs together',
    reaction: 'Legs glued shut. It topples like a felled tree.',
  },
  {
    word: 'WINGARDIUM LEVIOSA',
    tier: 3,
    spoken: [
      'wingardium leviosa', 'wingardium leviosar', 'win gardium leviosa',
      'wing hard him leviosa', 'wingardium levio sa', 'wing garden leviosa',
    ],
    color: 0xdfe8ff,
    glow: 0xffffff,
    damage: 12,
    speed: 40,
    radius: 2.0,
    effect: 'levitate',
    note: "it's leviOsa, not levioSA",
    reaction: 'Up it goes, slowly, looking betrayed.',
  },
  {
    word: 'SLUGULUS ERUCTO',
    tier: 3,
    spoken: [
      'slugulus eructo', 'sluggulus eructo', 'slug u lus eructo',
      'slugulus erupto', 'slug list eructo', 'sluggish eructo',
    ],
    color: 0x8fd67a,
    glow: 0xd8f5c8,
    damage: 24,
    speed: 38,
    radius: 0,
    effect: 'laugh',
    note: 'the slug-vomiting charm, regrettably',
    reaction: 'It is now producing slugs. Steadily. It has given up on you.',
  },
  {
    word: 'ANTEOCULATIA',
    tier: 3,
    spoken: [
      'anteoculatia', 'ante oculatia', 'anti oculatia', 'anteo culatia',
      'auntie oculatia', 'ante ocular tia',
    ],
    color: 0xc8a2ff,
    glow: 0xeadcff,
    damage: 22,
    speed: 46,
    radius: 0,
    effect: 'grow',
    note: 'grows antlers on it',
    reaction: 'It has antlers now. It keeps catching them on the walls.',
  },
  {
    word: 'OPPUGNO MAXIMA',
    tier: 3,
    spoken: [
      'oppugno maxima', 'oppugno maximus', 'opugno maxima', 'oh pugno maxima',
      'a pug no maxima', 'oppugno maximum',
    ],
    color: 0xffd27a,
    glow: 0xfff0cc,
    damage: 36,
    speed: 44,
    radius: 5.2,
    knockback: 4,
    note: 'sets the whole corridor on them',
    reaction: 'Everything loose in the corridor picks a side, and it is yours.',
  },
  {
    word: 'FINITE INCANTATEM',
    tier: 3,
    spoken: [
      'finite incantatem', 'finite incantatum', 'finight incantatem',
      'finity incantatem', 'finite in cantatem', 'finite incarnate them',
    ],
    color: 0xe8e8f8,
    glow: 0xffffff,
    damage: 34,
    speed: 56,
    radius: 4.0,
    note: 'ends whatever is going on, including it',
    reaction: 'Everything in the corridor stops at once.',
  },
  {
    word: 'SECTUMSEMPRA',
    tier: 3,
    spoken: [
      'sectumsempra', 'sectum sempra', 'section sempra', 'sectum semper',
      'sec tum sempra', 'seconds sempra',
    ],
    color: 0xff4a6a,
    glow: 0xffc0cc,
    damage: 50,
    speed: 60,
    radius: 0,
    pierce: true,
    note: 'the one you are not supposed to use',
    reaction: 'That one was not supposed to leave the book.',
  },
  {
    word: 'SERPENSORTIA',
    tier: 3,
    spoken: [
      'serpensortia', 'serpen sortia', 'serpent sortia', 'serpensortium',
      'serpents ortia', 'serpent sorta',
    ],
    color: 0x7ad88a,
    glow: 0xd0f4d8,
    damage: 26,
    speed: 42,
    radius: 2.4,
    effect: 'trip',
    note: 'conjures a snake at its feet',
    reaction: 'A snake. At its feet. It did not take it well.',
  },
  {
    word: 'PROTEGO MAXIMA',
    tier: 3,
    spoken: [
      'protego maxima', 'protego maximus', 'protect o maxima',
      'protego maximum', 'pro tego maxima', 'protego maxim a',
    ],
    color: 0xa0d8ff,
    glow: 0xdcf0ff,
    damage: 22,
    speed: 40,
    radius: 5.4,
    knockback: 9,
    note: 'a shield, expanded outward, rudely',
    reaction: 'The shield goes out instead of up. Everything moves.',
  },
  {
    word: 'SPECIALIS REVELIO',
    tier: 3,
    spoken: [
      'specialis revelio', 'specialist revelio', 'specialis revelia',
      'special is revelio', 'specialise revelio', 'specialis rebelio',
    ],
    color: 0xffe8a0,
    glow: 0xfff8dc,
    damage: 30,
    speed: 58,
    radius: 0,
    pierce: true,
    note: 'shows you what it is made of, from the inside',
    reaction: 'Now you can see exactly how it is put together.',
  },
  {
    word: 'HOMENUM REVELIO',
    tier: 3,
    spoken: [
      'homenum revelio', 'hominum revelio', 'homenum revelia',
      'home enum revelio', 'homonym revelio', 'hominem revelio',
    ],
    color: 0xd8c0ff,
    glow: 0xefe4ff,
    damage: 28,
    speed: 54,
    radius: 3.0,
    note: 'finds everything hiding, then hits it',
    reaction: 'Everything in the dark just got pointed at.',
  },
  {
    word: 'PIERTOTUM LOCOMOTOR',
    tier: 3,
    spoken: [
      'piertotum locomotor', 'pier totum locomotor', 'piertotum locomotive',
      'pier to tum locomotor', 'piertotem locomotor', 'peer totum locomotor',
    ],
    color: 0xc0c8d8,
    glow: 0xeaeef6,
    damage: 44,
    speed: 36,
    radius: 5.0,
    note: 'the castle stands up and helps',
    reaction: 'The statues have joined in. This is going well.',
  },
  {
    word: 'LACARNUM INFLAMARI',
    tier: 3,
    spoken: [
      'lacarnum inflamari', 'la carnum inflamari', 'lacarnum inflammare',
      'lacarnum inflamare', 'lack arnum inflamari', 'lacarnum in flamari',
    ],
    color: 0xff7a2a,
    glow: 0xffcc99,
    damage: 32,
    speed: 38,
    radius: 3.6,
    burn: true,
    note: 'sets its cloak alight',
    reaction: 'Its cloak is alight and it has nowhere to put it.',
  },
  {
    word: 'ARANIA EXUMAI',
    tier: 3,
    spoken: [
      'arania exumai', 'arania exumi', 'arrania exumai',
      'arania ex umai', 'a rania exumai', 'arania exuma',
    ],
    color: 0xffd060,
    glow: 0xfff0c0,
    damage: 38,
    speed: 50,
    radius: 3.4,
    knockback: 6,
    note: 'for spiders, and anything else with too many legs',
    reaction: 'Blasted back on all of its legs at once.',
  },
  {
    word: 'ALARTE ASCENDARE',
    tier: 3,
    spoken: [
      'alarte ascendare', 'alarte ascendere', 'alart ascendare',
      'a larte ascendare', 'alarte a scendare', 'alarty ascendare',
    ],
    color: 0xcfe8ff,
    glow: 0xf0f8ff,
    damage: 16,
    speed: 46,
    radius: 2.8,
    effect: 'levitate',
    note: 'launches everything nearby at the ceiling',
    reaction: 'The whole group is on the ceiling now.',
  },
  {
    word: 'CAVE INIMICUM',
    tier: 3,
    spoken: [
      'cave inimicum', 'cave in imicum', 'kave inimicum',
      'cavey inimicum', 'cave enemy come', 'cave inimicom',
    ],
    color: 0x9ae0c8,
    glow: 0xd8f6ec,
    damage: 24,
    speed: 44,
    radius: 4.6,
    knockback: 7,
    note: 'a boundary, drawn hard',
    reaction: 'A line is drawn, and it is on the wrong side of it.',
  },
  {
    word: 'AVADA KEDAVRA',
    tier: 3,
    spoken: [
      'avada kedavra', 'avada kadavra', 'avada kedabra',
      'a vada kedavra', 'avada ka davra', 'abracadabra kedavra',
    ],
    color: 0x5aff6a,
    glow: 0xc0ffc8,
    damage: 60,
    speed: 66,
    radius: 0,
    note: 'the one everybody knows, and nobody should',
    reaction: 'Green light. It stops being a problem.',
  },
  {
    word: 'VERDIMILLIOUS',
    tier: 3,
    spoken: [
      'verdimillious', 'verdi millious', 'verdimilious',
      'verde millious', 'verdi million', 'verdimillion',
    ],
    color: 0x6aff9a,
    glow: 0xc8ffd8,
    damage: 30,
    speed: 56,
    radius: 2.2,
    note: 'green sparks, fired in volume',
    reaction: 'Green sparks everywhere, none of them friendly.',
  },
  {
    word: 'BIBBIDI BOBBIDI BOO',
    tier: 3,
    spoken: [
      'bibbidi bobbidi boo', 'bibbity bobbity boo', 'bibbidi bobbidi bo',
      'biddy bobbidi boo', 'bibbidi bobbity boo', 'bibbedy bobbedy boo',
    ],
    color: 0x9ad8ff,
    glow: 0xdcf2ff,
    damage: 18,
    speed: 48,
    radius: 2.6,
    effect: 'shrink',
    note: 'from a different studio entirely',
    reaction: 'Turned into something small with a tail.',
  },
  {
    word: 'KLAATU BARADA NIKTO',
    tier: 3,
    spoken: [
      'klaatu barada nikto', 'klatu barada nikto', 'klaatu barada necktie',
      'klaatu verata nikto', 'clatu barada nikto', 'klaatu borada nikto',
    ],
    color: 0xb0ffd0,
    glow: 0xe0fff0,
    damage: 42,
    speed: 52,
    radius: 3.8,
    note: 'not from round here, and it still works',
    reaction: 'You mumbled part of it. It worked anyway. Mostly.',
  },
  {
    word: 'SOLVE ET COAGULA',
    tier: 3,
    spoken: [
      'solve et coagula', 'solve et coagulate', 'solvet coagula',
      'solve at coagula', 'solve et co agula', 'salve et coagula',
    ],
    color: 0xc8b0ff,
    glow: 0xe8dcff,
    damage: 34,
    speed: 42,
    radius: 3.0,
    effect: 'shrink',
    note: 'dissolve, and bring back together, smaller',
    reaction: 'Taken apart and reassembled at a discount.',
  },
  {
    word: 'TETRAGRAMMATON',
    tier: 3,
    spoken: [
      'tetragrammaton', 'tetra grammaton', 'tetragramaton',
      'tetra gramma ton', 'tetragrammatron', 'tetra grandmother ton',
    ],
    color: 0xffe0a0,
    glow: 0xfff4d8,
    damage: 48,
    speed: 40,
    radius: 4.2,
    note: 'four letters nobody is supposed to say out loud',
    reaction: 'You said the whole thing. Something enormous noticed.',
  },
  {
    word: 'FRIGORIFICUS',
    tier: 3,
    spoken: [
      'frigorificus', 'frigori ficus', 'frigorific us',
      'frigo rificus', 'frigerificus', 'refrigerator ficus',
    ],
    color: 0xb0e8ff,
    glow: 0xe4f8ff,
    damage: 22,
    speed: 48,
    radius: 3.8,
    effect: 'freeze',
    note: 'drops the temperature past the point of argument',
    reaction: 'Everything in range is now considerably colder.',
  },
  {
    word: 'GRAVITAS MAXIMA',
    tier: 3,
    spoken: [
      'gravitas maxima', 'gravitas maximus', 'gravity as maxima',
      'gravitas maxim a', 'gravitas maximum', 'gravity ass maxima',
    ],
    color: 0x8a90b0,
    glow: 0xd0d6ec,
    damage: 30,
    speed: 34,
    radius: 4.4,
    effect: 'trip',
    note: 'makes it much too heavy for its own legs',
    reaction: 'Far too heavy for its own legs. They folded.',
  },
  {
    word: 'VORTEX MAXIMUS',
    tier: 3,
    spoken: [
      'vortex maximus', 'vortex maxima', 'vor tex maximus',
      'vortex maximum', 'vortec maximus', 'four tex maximus',
    ],
    color: 0x7ad0ff,
    glow: 0xd0eeff,
    damage: 28,
    speed: 30,
    radius: 6.0,
    knockback: 8,
    note: 'a whirlwind, filling the corridor',
    reaction: 'The corridor has a whirlwind in it and they are all in it.',
  },
  {
    word: 'TENEBRIS UMBRA',
    tier: 3,
    spoken: [
      'tenebris umbra', 'tene bris umbra', 'tenebras umbra',
      'tenebris umber', 'tenebrous umbra', 'ten a bris umbra',
    ],
    color: 0x7a6ab0,
    glow: 0xc8bce8,
    damage: 26,
    speed: 46,
    radius: 3.2,
    effect: 'freeze',
    note: 'the dark, made solid and thrown',
    reaction: 'The dark closed over it and held on.',
  },
  {
    word: 'ELBERETH GILTHONIEL',
    tier: 3,
    spoken: [
      'elbereth gilthoniel', 'elbereth gilthonial', 'elberith gilthoniel',
      'el bereth gilthoniel', 'elbereth gil thoniel', 'elbereth guilt on eel',
    ],
    color: 0xe8f0ff,
    glow: 0xffffff,
    damage: 46,
    speed: 44,
    radius: 4.8,
    note: 'a star-name, from a different set of books again',
    reaction: 'A star answers. Everything in the corridor flinches.',
  },
]

/**
 * The pool this floor draws from.
 *
 * Floor 1 is tier 1 only; tier 2 joins at floor 2, tier 3 at floor 4. After
 * that everything is in the bag and the tongue-twisters get more likely.
 */
export function spellsForFloor(floor) {
  const maxTier = floor >= 4 ? 3 : floor >= 2 ? 2 : 1
  const pool = SPELLS.filter(s => s.tier <= maxTier)
  if (maxTier < 3) return pool
  // Weight the hard ones up as the floors climb, so late game is a mouthful.
  const extra = Math.min(3, Math.floor((floor - 4) / 2))
  return pool.concat(...Array.from({ length: extra }, () => SPELLS.filter(s => s.tier === 3)))
}
